# Generated by Django 4.1 on 2022-10-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('username', models.CharField(default=None, max_length=30, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('golongan_darah', models.CharField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=100)),
                ('tanggal_lahir', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('is_verivicate', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
