# Generated by Django 4.1 on 2022-10-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='jenis_kelamin',
            field=models.CharField(max_length=100),
        ),
    ]
