# Generated by Django 4.1.2 on 2022-11-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hasilScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaDonor', models.CharField(max_length=255)),
                ('suhuTubuh', models.IntegerField()),
                ('tekananDarah', models.IntegerField()),
                ('kadarHemo', models.IntegerField()),
                ('beratBadan', models.IntegerField()),
            ],
        ),
    ]
