# Generated by Django 4.1 on 2022-11-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_customuser_blood_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
