# Generated by Django 4.1 on 2022-11-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationuser',
            name='is_validate',
        ),
    ]
