# Generated by Django 4.1 on 2022-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_informationuser_is_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationuser',
            name='by_validate',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
