# Generated by Django 4.1.2 on 2022-10-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0002_alter_jadwal_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='month',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='year',
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='date',
            field=models.DateField(),
        ),
    ]
